# Generated by Django 5.2.17 on 2026-09-20 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('google_form_id', models.CharField(max_length=255, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('max_game_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('not_now', 'Not Now'), ('please_remove', 'Please Remove')], default='active', max_length=20)),
                ('earliest_invite_lead', models.DurationField(blank=True, null=True)),
                ('latest_invite_lead', models.DurationField(blank=True, null=True)),
                ('event_cooldown', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_question_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=160)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='planner.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_value', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=160)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='planner.formquestion')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_response_id', models.CharField(max_length=255, unique=True)),
                ('submitted_name', models.CharField(blank=True, max_length=160)),
                ('submitted_email', models.EmailField(blank=True, max_length=254)),
                ('submitted_at', models.DateTimeField()),
                ('raw_response_data', models.JSONField(default=dict)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='planner.form')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='planner.person')),
            ],
        ),
        migrations.CreateModel(
            name='FormRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='planner.form')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_requests', to='planner.person')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formquestion',
            constraint=models.UniqueConstraint(fields=('form', 'google_question_id'), name='unique_google_question_per_form'),
        ),
        migrations.AddConstraint(
            model_name='formquestionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'google_value'), name='unique_google_value_per_question'),
        ),
    ]
