# Generated by Django 5.2.17 on 2026-09-22 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_item_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=160)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='planner.form')),
            ],
        ),
        migrations.AddField(
            model_name='formquestion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='planner.formquestiongroup'),
        ),
    ]
