# Generated by Django 5.2.17 on 2026-09-22 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_formquestiongroup_formquestion_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='formquestion',
            name='hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_questions', to='planner.hour'),
        ),
    ]
