# Generated by Django 5.2.17 on 2026-09-23 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_day_formquestionchoice_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formquestiongroup',
            name='day',
        ),
        migrations.CreateModel(
            name='FormQuestionGroupChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_value', models.CharField(max_length=500)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_question_group_choices', to='planner.day')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='planner.formquestiongroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'google_value'), name='unique_google_value_per_question_group')],
            },
        ),
    ]
