# Generated by Django 5.2.17 on 2026-09-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_remove_formquestiongroup_day_formquestiongroupchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
