# Generated by Django 5.2.17 on 2026-09-23 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duration',
            name='duration',
        ),
        migrations.AddField(
            model_name='duration',
            name='days',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formquestionchoice',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_question_choices', to='planner.duration'),
        ),
    ]
