# Generated by Django 5.2.17 on 2026-09-23 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_remove_duration_duration_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='guest_games',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='event_cooldown',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=7), null=True),
        ),
    ]
