# Generated by Django 5.2.17 on 2026-09-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_person_guest_games_alter_person_event_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='game_types',
            field=models.ManyToManyField(blank=True, related_name='interested_people', to='planner.gametype'),
        ),
        migrations.AddField(
            model_name='person',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='interested_people', to='planner.game'),
        ),
        migrations.AddField(
            model_name='person',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='people', to='planner.platform'),
        ),
        migrations.CreateModel(
            name='DayHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_hours', to='planner.day')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_hours', to='planner.hour')),
            ],
            options={
                'ordering': ['day__order', 'hour__time'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='availability',
            field=models.ManyToManyField(blank=True, related_name='available_people', to='planner.dayhour'),
        ),
        migrations.AddConstraint(
            model_name='dayhour',
            constraint=models.UniqueConstraint(fields=('day', 'hour'), name='unique_day_hour'),
        ),
    ]
