# Generated by Django 5.2.17 on 2026-09-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_person_game_types_person_games_person_platforms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='google_response_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='formsubmission',
            constraint=models.UniqueConstraint(fields=('form', 'google_response_id', 'submitted_at'), name='unique_form_submission_revision'),
        ),
    ]
