# Generated by Django 5.2.17 on 2026-09-29 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_alter_formsubmission_google_response_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formrequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
