# Generated by Django 5.2.17 on 2026-09-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_alter_formrequest_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='survey_url',
            field=models.URLField(blank=True),
        ),
    ]
