# Generated by Django 5.2.17 on 2026-09-30 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_form_survey_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_spans', to='planner.day')),
                ('day_hours', models.ManyToManyField(related_name='time_spans', to='planner.dayhour')),
                ('end_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_time_spans', to='planner.hour')),
                ('start_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_time_spans', to='planner.hour')),
            ],
            options={
                'ordering': ['day__order', 'start_hour__time', 'end_hour__time'],
                'constraints': [models.UniqueConstraint(fields=('day', 'start_hour', 'end_hour'), name='unique_time_span')],
            },
        ),
    ]
