# Generated by Django 5.2.17 on 2026-09-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_timespan'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='expected_duration_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
