# Generated by Django 5.2.17 on 2026-09-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_game_expected_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
