# Generated by Django 5.2.17 on 2026-10-01 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_game_max_players_game_min_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('happened', models.BooleanField(blank=True, default=None, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='planner.game')),
                ('time_span', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='planner.timespan')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField()),
                ('plus_ones', models.PositiveSmallIntegerField(default=0)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('attending', 'Attending'), ('attended', 'Attended'), ('flaked', 'Flaked'), ('waiting', 'Waiting')], default='pending', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='planner.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='planner.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'person'), name='unique_person_event_invitation')],
            },
        ),
    ]
