# Generated by Django 5.2.17 on 2026-10-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_event_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='led_events', to='planner.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Member', 'Member')], default='Member', max_length=20),
        ),
    ]
