# Generated by Django 5.2.17 on 2026-10-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_event_leader_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='boardgamegeek_url',
            field=models.URLField(blank=True),
        ),
    ]
